print("Nombre del alumno")
print("Diego Armando Garcia Castillo")
print("Lugar de recidencia")
print("Rincón de Romos, Ags")
print("Fecha de nacimiento")
print("28 de noviembre de 2002")
print("Color favorito")
print("Azul Cian")
print("Animal favorito")
print("Gatos")
print("¿Qué es programación?")
print("Es el proceso de creación de programas informaticos. Es el traducir los deseos de una persona al lenguaje de la máquina")
print("¿Por qué es importante la programación?")
print("Es fundamental para acrecentar el avance tecnológico dentro de las industrias para crea sitios de aplicaciones creadas a partir de códigos")
print("Explique con sus palabras que es herencia")
print("Es el concepto de programación que va dirigido hacia los objetos, el cual permite derivar una clase a otra clase")
print("Explique con sus palabras que es poliformismo")
print("Es la capacidad que tienen algunos lenguajes para que al enviar el mismo mensaje cada uno de los objetos pueda responder ese mensaje")
print("Explique con sus palabras que es abstracción")
print("Esta función consiste en aislar un elemento de su contexto o del resto de los elementos que lo acompañan")
print("Explique con sus palabras que es encapsulamiento")
print("Es la función que oculta el estado, es decir, que los datos del miemdro de manera en que solo se puedan modificar mediante laas operaciónes definidas para este objeto")