#Programa que te pida el semestre en el que estás y que te imprima las materias y créditos de cada semestre.

semestre = int(input("¿En que semestre estás?: "))

if semestre == 1:
	print("Las materias son: ")
	print("Calculo diferencial")
	print("Fundamentos de programación")
	print("Matemáticas discretas I")
	print("Introducción a las Tic")
	print("Taller de Ética")
	print("Fundamentos de investigación")
	print("Inglés I")
	print("Créditos de tu semestre: 26")
elif semestre == 2:
	print("Las materias son: ")
	print("Calculo integral")
	print("Programación orientada a objetos")
	print("Matemáticas discretas II")
	print("Probabilidad y estadistica")
	print("Contabilidad y costos")
	print("Inglés II")
	print("Creditos de tu semestre: 25")
elif semestre == 3:
	print("Las materias son: ")
	print("Matemáticas aplicadas a comunicaciónes")
	print("Estructura y organización de datos")
	print("Administración gerencial")
	print("Fundamentos de base de datos")
	print("Electicidad y magnetismo")
	print("Álgebra lineal")
	print("Inglés III")
	print("Créditos de tu semestre: 27")
elif semestre == 4:
	print("Las materias son: ")
	print("Matemáticas aplicadas a comunicaciónes")
	print("Estructura y organización de datos")
	print("Administración gerencial")
	print("Fundamentos de base de datos")
	print("Electicidad y magnetismo")
	print("Álgebra lineal")
	print("Inglés III")
	print("Créditos de tu semestre: 28")
elif semestre == 5:
	print("Las materias son:")
	print("Análisis de señales y sistemas")
	print("Programación II")
	print("Matemáticas para la toma de decisiones")
	print("Taller de base de datos")
	print("Circuitos eléctricos y electrónicos")
	print("Ingenieria de Software")
	print("Inglés IV")
	print("Créditos de tu semestre: 28")
elif semestre == 6:
	print("Las materias son:")
	print("Redes de computadoras")
	print("Programación web")
	print("Desarrollo de emprendedores")
	print("Taller de investigación I")
	print("Sistemas Operativos I")
	print("Tecnologías inalambricas")
	print("Créditos de tu semestre: 27")
elif semestre == 7:
	print("Las materias son:")
	print("Redes emergentes")
	print("Desarrollo de aplicaciónes para Dins. M")
	print("Desarrollo sustentable")
	print("Taller de unvestigación II")
	print("Sistemas Operativos II")
	print("Negocios electrónicos I")
	print("Créditos de tu semestre: 28")
elif semestre == 8:
	print("Las materias son:")
	print("Administración y seguridad de redes")
	print("Auditoría en tecnologías de la información")
	print("Interacción Humano-Computadora")
	print("Ingeniería del conocimiento")
	print("Negocios electrónicos II")
	print("Créditos de tu semestre: 21")
elif semestre == 9:
	print("Las materias son: ")
	print("Actividades Complementarias")
	print("Especialidad")
	print("Residencias Profesionales")
	print("Servicio Social")
else:
	print("Error")
	print("Fin")